### PR TITLE
Update demos to use 2 new tags on top and back of driller

### PR DESCRIPTION
**Pull request by longhathuc**

### CODE REVIEW

**Comment by florent-lamiraux** [comment]
Can you remove binary file  tiago/deburring/tiago_fov.pyc ?

**Review by longhathuc — COMMENTED** [review]
pyc files removed

**Comment by florent-lamiraux** [comment]
Thank you can you change the branch from `master` to `devel` ?

**Comment by longhathuc** [comment]
I have changed the destination (base) branch

**Comment by florent-lamiraux** [comment]
Thank you.

**Pull request merged**
