### PR TITLE
[talos/manipulate_boxes] Add early stages of visual feedback.

### PR DESCRIPTION
**Pull request by jmirabel**
This adds a visual feedback to the demo. To play with it, you can use the command (with different values of course)
`rosrun tf2_ros static_transform_publisher 0. 0. 0. 0. 0. 0. box/base_link box_rviz/base_link`

You should be able to run it on your computer.

In agimus, you need on the PR I just opened: https://github.com/pulls?utf8=%E2%9C%93&q=is%3Aopen+is%3Apr+archived%3Afalse+user%3Aagimus+

In SoT, the only mandatory change is https://github.com/stack-of-tasks/dynamic_graph_bridge/pull/60

### CODE REVIEW

**Comment by florent-lamiraux** [comment]
I fetched the various PR and tried
`rosrun tf2_ros static_transform_publisher 0. 0. 0. 0. 0. 0. box/base_link box_rviz/base_link`,
but even with 0 error, when reaching the pregrasp position, the controller starts diverging.

pyrene

**Comment by florent-lamiraux** [comment]
It seems to work, however my Pyrene does not have any tag on the hand. I guess there is another package to update ?

**Comment by jmirabel** [comment]
The tags on the hand are added by the estimation.launch file. In RViz, you should have entities called *tag36_11_000[56][0123]*. The DAE of the tags are in gerard-bauzil package. You may have forgotten to update it ? If you did, you may have an issue with CMakeCache (not regenerating the list of files in a directory).

**Comment by jmirabel** [comment]
The DAE files are installed in *<install_dir>/share/gerard_bauzil/meshes/apriltag_36h11/tag36_11_<tag_id>.dae*

**Pull request merged**
